language: python
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install tcl tk
    - sudo apt-get install python-tk
    - sudo apt-get install -qq python-numpy python-scipy
python:
  - "2.7"
  - "3.4"
# command to install dependencies
install: "pip install -r requirements.txt --use-mirrors"
# command to run tests
script: nosetests

virtualenv:
  system_site_packages: true
