language: python

matrix:
  include:
    - python: "3.6"
    - python: "3.7"
      dist: xenial

addons:
  apt:
    packages:
      - libhdf5-serial-dev


before_install:
  - export MPLBACKEND=agg
  - pip install --upgrade pip

install:
  - pip install restructuredtext-lint sphinx~=1.8 pygments
  # make sure tables and h5py get linked vs the same hdf5 library
  - pip install --no-binary=h5py --no-binary=tables .

script:
  - python setup.py test
  - rst-lint README.rst
  - python setup.py build_sphinx


deploy:
  - provider: pypi
    skip_cleanup: true
    distributions: sdist
    user: fact-deploybot
    password:
      secure: "HjD8z63sITDhK4TwcnF/q1K+nF3nIslpoVUdJhSKlX/Hv8NaFajt0bM32KqIEADMAj510dcuHlZtcyDCX/9TTF4U9fAPkZSsoAa4yyD7BwcY2arwHDBgYSvGAHTqCzMwZvNcE+k0A7ZhfqjwwW+dtMM7Hx+vS+MfqhXy6ZrLbEg="
    on:
      branch: master
      tags: true
      condition: $TRAVIS_PYTHON_VERSION = "3.6"
