language: python
before_install:
    sudo apt-get update -qq
    sudo apt-get install libblas-dev libatlas-dev liblapack-dev
    sudo apt-get install tcl tk
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: nosetests
